
version: "3.8"
name: "z2m-devices-integration-tests"

services:
  mosquitto:
      image: eclipse-mosquitto:latest
      volumes:
        - ./mosquitto:/mosquitto
        - ./mosquitto/data:/mosquitto/data
        - ./mosquitto/log:/mosquitto/log
      ports:
        - "1883:1883"
      restart: unless-stopped